# Generated by Django 5.1.2 on 2025-04-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='RUT')),
                ('seg_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('apellido_p', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_m', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, unique=True, verbose_name='RUT')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoProveedor',
            fields=[
                ('id_tipo_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Proveedor')),
            ],
            options={
                'verbose_name': 'Tipo de Proveedor',
                'verbose_name_plural': 'Tipos de Proveedores',
            },
        ),
        migrations.CreateModel(
            name='TipoRecibo',
            fields=[
                ('id_tipo_rec', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Recibo')),
            ],
            options={
                'verbose_name': 'Tipo de Recibo',
                'verbose_name_plural': 'Tipos de Recibos',
            },
        ),
        migrations.CreateModel(
            name='Establecimientos',
            fields=[
                ('id_est', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rbd', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos', to='docs.directores')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'unique_together': {('rbd', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('numero_servicio', models.CharField(max_length=100, verbose_name='Número de Servicio')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='docs.establecimientos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='docs.proveedor')),
                ('tipo_recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='docs.tiporecibo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'unique_together': {('numero_servicio', 'proveedor', 'establecimiento')},
            },
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='docs.tipoproveedor'),
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('numero_recibo', models.CharField(max_length=100, verbose_name='Número de Factura o Boleta')),
                ('fecha_envio_pago', models.DateField(verbose_name='Fecha de Envío a Pago')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Interés')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='docs.servicios')),
            ],
            options={
                'verbose_name': 'Registro de Servicio',
                'verbose_name_plural': 'Registros de Servicios',
                'unique_together': {('servicio', 'numero_recibo')},
            },
        ),
    ]
