# Generated by Django 5.1.2 on 2025-04-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_registroservicio_fecha_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.AddField(
            model_name='establecimientos',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos', to='docs.comunas'),
        ),
    ]
