# Generated by Django 5.1.2 on 2025-05-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_comunas_establecimientos_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='acronimo',
            field=models.CharField(default='ADA', max_length=10, verbose_name='Acrónimo'),
        ),
    ]
