# Generated by Django 5.1.2 on 2025-10-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_proveedor_acronimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroservicio',
            name='interes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Interés'),
        ),
        migrations.AlterField(
            model_name='registroservicio',
            name='monto',
            field=models.IntegerField(verbose_name='Monto'),
        ),
    ]
