# Generated by Django 5.1.2 on 2025-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_registroservicio_interes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimientos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
