# Generated by Django 5.1.2 on 2025-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_add_activo_to_establecimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'permissions': [('ver_dashboard', 'Puede ver dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='directores',
            options={'permissions': [('ver_director', 'Puede ver director'), ('editar_director', 'Puede editar director'), ('eliminar_director', 'Puede eliminar director'), ('crear_director', 'Puede crear director')], 'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='establecimientos',
            options={'permissions': [('ver_establecimiento', 'Puede ver establecimiento'), ('editar_establecimiento', 'Puede editar establecimiento'), ('eliminar_establecimiento', 'Puede eliminar establecimiento'), ('crear_establecimiento', 'Puede crear establecimiento')], 'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': [('ver_proveedor', 'Puede ver proveedor'), ('editar_proveedor', 'Puede editar proveedor'), ('eliminar_proveedor', 'Puede eliminar proveedor'), ('crear_proveedor', 'Puede crear proveedor')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='registroservicio',
            options={'permissions': [('ver_registro', 'Puede ver registro'), ('editar_registro', 'Puede editar registro'), ('eliminar_registro', 'Puede eliminar registro'), ('crear_registro', 'Puede crear registro')], 'verbose_name': 'Registro de Servicio', 'verbose_name_plural': 'Registros de Servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'permissions': [('ver_servicio', 'Puede ver servicio'), ('editar_servicio', 'Puede editar servicio'), ('eliminar_servicio', 'Puede eliminar servicio'), ('crear_servicio', 'Puede crear servicio')], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
