# Generated by Django 5.1.2 on 2025-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_dashboardview_alter_directores_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'PermisosProxy',
                'verbose_name_plural': 'PermisosProxys',
                'permissions': [('ver_dashboard', 'Puede ver dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='DashboardView',
        ),
    ]
