# Generated by Django 5.1.2 on 2025-10-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_permisosproxy_delete_dashboardview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisosproxy',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver dashboard'), ('Acceso_a_reportes', 'Puede acceder a reportes')], 'verbose_name': 'PermisosProxy', 'verbose_name_plural': 'PermisosProxys'},
        ),
    ]
